version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2-jdk-node-browsers-legacy

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle test

  deploy-integracao:
      docker:
        - image: buildpack-deps:trusty
      steps:
        - checkout
        - run:
            name: Deploy para o ambiente de integracao
            command: |
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_INTEGRATION_APP_NAME.git master

workflows:
  version: 2
  standard-build:
    jobs:
      - build
      - deploy-integracao:
          requires:
            - build
          filters:
            branches:
              only: master
